### ISSUE TITLE
Typo in setup.py

### ISSUE THREAD

**Issue by Roxysteve** [francescortiz/image#5]
Attempting to install Image on a raspberry Pi2 using "sudo pip-3.2 install Image".

Install fails because of a reported typo at the "Author" line of the setup.py file.

**Comment by francescortiz** [comment]
Image does not work on python 3 yet. Also, when it does I don't think it will be compatible with python 3.2 or lower versions of python 3. check https://www.python.org/dev/peps/pep-0414/

**Comment by Roxysteve** [comment]
Sorry to bother you, then. Thanks for the reply.

Steve Mann

**Comment by francescortiz** [comment]
No problem at all. You are welcome.
